### ISSUE TITLE
births should depend on current population

### ISSUE THREAD

**Issue by Translucent504** [mm103434/Simple_Simulation#13]
Like adding a factor of (1/100) * population * births rounded up. so if the random births is 5 and population is 1000 the number of births will be 50. Like as if 1% of the population gives birth in every interval.

**Comment by KIRA009** [comment]
Absolutely true. Thanks for bringing it up

**Comment by ShadowMuffin** [comment]
If nobody is gonna do it I got it

**Comment by KIRA009** [comment]
What are you planning to do?

**Comment by ShadowMuffin** [comment]
well the thing when the population only starts it is impossible to use a certain percentage of the population as value, so until there are ~1000 people in the community, births (and deaths) per day will remain like before. Once it hits 1000, the randint() will take a percentage of the population instead of (5,10), like Translucent's comment points out

**Comment by KIRA009** [comment]
Okay, then carry on

**Comment by ShadowMuffin** [comment]
pull request is on
